### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by ymc-sise** [turboMaCk/Babylon-Grid#11]
Please fix line 300 in jquery.babylongrid.js
from
            $(this.element).html('');
to
            $(this.element).find('.babylongrid-container').html('');

Otherwise reload deletes all the content.

and change line 309  .off('babylongrid:reset') to .off('babylongrid:reload') in the destructor. This listener does not exist.

**Comment by turboMaCk** [comment]
@ymc-sise Can you an open pull request for those changes?

**Comment by turboMaCk** [comment]
new version released, thanks!
