### ISSUE TITLE
Complete/Done callback

### ISSUE THREAD

**Issue by kmike1** [turboMaCk/Babylon-Grid#2]
Is there a way to trigger other method after grid resizing ends?

**Comment by turboMaCk** [comment]
@kmike1 Nope, I do not think so. Do you want to send pull request on this feature?

**Comment by kmike1** [comment]
Sure, it will be very useful for me. Now found workaround with setTimeout but this isnt best solution.

**Comment by turboMaCk** [comment]
@kmike1 Done in `2.2` https://github.com/turboMaCk/Babylon-Grid/commit/c5d0f8e04c63c4040007f4bda3608795745b6f89
