### ISSUE TITLE
No possibility to reset the grid

### ISSUE THREAD

**Issue by ymc-sise** [turboMaCk/Babylon-Grid#6]
Hi
Currently I am using your grid for a search. I have the requirement to first clear the grid for a new search and then add the search results. Therefore I need a possibility to clear the cached articles.

How about adding the following code?

```
$(this.element).on('babylongrid:remove', function() {
    self._removeArticles();
});

/*
 Remove articles
 */
_removeArticles: function() {
    this.cached.articles = [];
    this._setColumns(this.__currentColumns);
},
```

**Comment by turboMaCk** [comment]
Do you want to send PR on this?

**Comment by turboMaCk** [comment]
done in: https://github.com/turboMaCk/Babylon-Grid/commit/d8ba8070698581429d8d42e7a0f2ab777f896c43
